### PR TITLE
unicode-display_width for Unicode v7.0.0

### LINKED ISSUE #4: Loose version constraint for gem `unicode-display_width`
Unless it's incompatible

### PR DESCRIPTION
**Pull request by skull-squadron**
Closes #4

### CODE REVIEW

**Comment by PikachuEXE** [comment]
:+1: 
I guess the min version is to avoid https://github.com/janlelis/unicode-display_width/issues/1 right?

**Comment by skull-squadron** [comment]
Yeah, thinking again... might want to just bump the requirement to `'>= 0.2.0', '< 1.0'` considering 0.1.1 uses a really old version of Unicode, so that hirb-unicode Just Works :tm:.

**Comment by PikachuEXE** [comment]
Wondering if the author is still active

**Comment by skull-squadron** [comment]
If not, feel free to use:

``` ruby
gem 'hirb-unicode', github: 'steakknife/hirb-unicode', branch: 'update__unicode-display_width'
```

Or using [specific_install](https://github.com/rdp/specific_install)

```
gem specific_install http://github.com/steakknife/hirb-unicode.git -b update__unicode-display_width
```

Hope so though.

**Comment by PikachuEXE** [comment]
Starting to think GitHub should have some method to allow people to "claim" an inactive repo :S

**Comment by skull-squadron** [comment]
@PikachuEXE Srrly, like voting to elect new owner/s, but forking is usually the way to go.  For gems, they need an election system, otherwise fork to `hirb-unicode-{{your handle}}`

**Comment by PikachuEXE** [comment]
That's true, forgot :3
I guess I mean ruby gems actually :X

**Comment by skull-squadron** [comment]
`gem install hirb-unicode-steakknife` or `gem 'hirb-unicode-steakknife'`

**Pull request closed without merging**
